import { useContext, useEffect } from "react";
import { useCustomState } from "../../Variables/stateVariables";
import { State } from "../context/ContextSales";
import { getSpecificSaleProduct } from "../../actions/saleProductAction";

export default function Dates({ selectedPrinter }) {
  const { invoicedata, setInvoicedata, loading, setLoading } =
    useCustomState();
  const { salesId } = useContext(State);

  useEffect(() => {
    // console.log(salesId);

    getspecificDataforInvoice();
  }, []);

  const getspecificDataforInvoice = async () => {
    let result = await getSpecificSaleProduct(salesId);
    console.log('hice')
    // console.log(result);
    setInvoicedata(result?.data);
    setLoading(true);
  };

  return (
    <>
      {loading ? (
        <>
          {selectedPrinter === "thermal" ? (
            <div
              style={{
                width: "100%",
                overflowX: "auto",
                marginTop: "-30px",
                marginBottom: "0px",
                whiteSpace: "nowrap",
              }}
            >
              <table
                className="mt-10 table1"
                style={{ fontSize: "10px", whiteSpace: "nowrap" }}
              >
                <tbody>
                  <tr
                    style={{
                      marginTop: "-10px",
                      padding: "0px",
                      marginBottom: "-10px",
                    }}
                  >
                    <td>
                      <span className="font-bold td1">
                        Customer Name:{invoicedata?.customerName}
                      </span>
                    </td>
                  </tr>
                  <tr style={{ marginTop: "-30px", marginBottom: "0px" }}>
                    <td
                      className="font-bold td1"
                      style={{ marginTop: "-30px", marginBottom: "0px" }}
                    >
                      <span className="font-bold td1">Invoicer number:</span>{" "}
                      {invoicedata?.id}
                    </td>
                  </tr>
                  <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
                    <td className="font-bold td1">
                      <span className="font-bold td1">
                        {" "}
                        Cell No:{invoicedata?.customerNumber}
                      </span>
                    </td>
                  </tr>
                  <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
                    <td>
                      <span className="font-bold td1">Invoice date:</span>
                      {new Date(invoicedata?.createdAt).toLocaleDateString(
                        "en-GB"
                      )}
                    </td>
                  </tr>
                  <tr style={{ marginTop: "0px", marginBottom: "0px" }}>
                    <td>
                      {" "}
                      <span className="font-bold td1">Generated By:</span>
                      {invoicedata?.saleBy}
                    </td>
                  </tr>
                  <tr style={{ marginTop: "0px", marginBottom: "0px" }}>
                    <td className="td1">
                      <span className="font-bold td1">
                        FBR Invoicer Number:
                      </span>{" "}
                      {invoicedata?.invoiceNumber}
                    </td>
                  </tr>
                  <tr>
                    <td>
                      {" "}
                      <span className="font-bold td1">Generated By:</span>{" "}
                      &nbsp;{invoicedata?.saleBy}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          ) : (
              <table style={{whiteSpace:"nowrap",justifyContent: "center", marginTop: "20px", marginLeft: "100px", borderBottom: "2px solid black"}}>
                <tr>
                  <td>
                  <span className="font-bold td1" >Customer Name:&nbsp;&nbsp;</span>{invoicedata?.customerName}
                  </td>
                  <td>
                    <span className="font-bold td1" style={{ marginLeft: "80px"}}>Invoicer number:&nbsp;&nbsp;</span>{" "}
                    {invoicedata?.id}
                  </td>
                </tr>
                <tr>
                  <td>
                  <span className="font-bold td1">Cell No:&nbsp;&nbsp;</span>{invoicedata?.customerNumber}
                  </td>
                  <td >
                    <span className="font-bold td1" style={{ marginLeft: "80px"}}>Invoice date:&nbsp;&nbsp;</span>
                    {new Date(invoicedata?.createdAt).toLocaleDateString(
                      "en-GB"
                    )}
                  </td>
                </tr>
                <tr>
                  <td >
                  <span className="font-bold td1">Generated By:&nbsp;&nbsp;</span>{invoicedata?.saleBy}
                  </td>
                  <td >
                    <span className="font-bold td1" style={{ marginLeft: "80px"}}>FBR Invoicer Number:&nbsp;&nbsp;</span>{" "}
                    {invoicedata?.invoiceNumber}
                  </td>
                </tr>
              </table>
          )}
        </>
      ) : (
        <h1></h1>
      )}
    </>
  );
}
