import { useContext, useEffect } from "react";
import { useCustomState } from "../../Variables/stateVariables";
import { State } from "../context/ContextSales";
import { getSpecificSaleProduct } from "../../actions/saleProductAction";

export default function Dates({ selectedPrinter }) {
  const { invoicedata, setInvoicedata, loading, setLoading } = useCustomState();
  const { salesId } = useContext(State);

  useEffect(() => {
    // console.log(salesId);

    getspecificDataforInvoice();
  }, []);

  const getspecificDataforInvoice = async () => {
    let result = await getSpecificSaleProduct(salesId);
    console.log("hice");
    // console.log(result);
    setInvoicedata(result?.data);
    setLoading(true);
  };

  return (
    <>
      {loading ? (
        <>
          {selectedPrinter === "thermal" ? (
            <div
              style={{
                width: "100%",
                overflowX: "auto",
                marginTop: "-30px",
                marginBottom: "0px",
                whiteSpace: "nowrap",
              }}
            >
              <table
                className="mt-10 table1"
                style={{ fontSize: "10px", whiteSpace: "nowrap" }}
              >
                <tbody>
                  <tr
                    style={{
                      marginTop: "-10px",
                      padding: "0px",
                      marginBottom: "-10px",
                    }}
                  >
                    <td>
                      <span className="font-bold td1">
                        Customer Name:{invoicedata?.customerName}
                      </span>
                    </td>
                  </tr>
                  <tr style={{ marginTop: "-30px", marginBottom: "0px" }}>
                    <td
                      className="font-bold td1"
                      style={{ marginTop: "-30px", marginBottom: "0px" }}
                    >
                      <span className="font-bold td1">Invoicer number:</span>{" "}
                      {invoicedata?.id}
                    </td>
                  </tr>
                  <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
                    <td className="font-bold td1">
                      <span className="font-bold td1">
                        {" "}
                        Cell No:{invoicedata?.customerNumber}
                      </span>
                    </td>
                  </tr>
                  <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
                    <td>
                      <span className="font-bold td1">Invoice date:</span>
                      {new Date(invoicedata?.createdAt).toLocaleDateString(
                        "en-GB"
                      )}
                    </td>
                  </tr>
                  <tr style={{ marginTop: "0px", marginBottom: "0px" }}>
                    <td>
                      {" "}
                      <span className="font-bold td1">Generated By:</span>
                      {invoicedata?.saleBy}
                    </td>
                  </tr>
                  <tr style={{ marginTop: "0px", marginBottom: "0px" }}>
                    <td className="td1">
                      <span className="font-bold td1">
                        FBR Invoicer Number:
                      </span>{" "}
                      {invoicedata?.invoiceNumber}
                    </td>
                  </tr>
                  <tr>
                    <td>
                      {" "}
                      <span className="font-bold td1">Generated By:</span>{" "}
                      &nbsp;{invoicedata?.saleBy}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          ) : (
            <>
              <div className="InvoiceLaserFirstRecordDiv">
                <div className="consolidateLaserQuantity">
                  <h5>Customer Name:</h5>
                  <p>{invoicedata?.customerName}</p>
                </div>
                <div className="consolidateLaserProductCode">
                  <h5>Invoicer number:</h5>
                  <p>{invoicedata?.id}</p>
                </div>
              </div>
              <div className="InvoiceLaserFirstRecordDiv">
                <div className="consolidateLaserQuantity">
                  <h5>Cell No:</h5>
                  <p>{invoicedata?.customerNumber}</p>
                </div>
                <div className="consolidateLaserProductCode">
                  <h5>Invoice date:</h5>
                  <p>
                    {new Date(invoicedata?.createdAt).toLocaleDateString(
                      "en-GB"
                    )}
                  </p>
                </div>
              </div>
              <div className="InvoiceLaserFirstRecordDiv">
                <div className="consolidateLaserQuantity">
                  <h5>Generated By:</h5>
                  <p>{invoicedata?.saleBy}</p>
                </div>
                {invoicedata?.invoiceNumber ? (
                  <>
                    <div className="consolidateLaserProductCode">
                      <h5>FBR Invoicer Number:</h5>
                      <p> {invoicedata?.invoiceNumber}</p>
                    </div>
                  </>
                ) : (
                  <></>
                )}
              </div>
            </>
          )}
        </>
      ) : (
        <h1></h1>
      )}
    </>
  );
}
