import { useContext } from "react";
import { useEffect } from "react";
import { Statee } from "./context/stateContext";
import "../stylee/tableStyling.css";

import { useSelector } from "react-redux";
export default function Dates({ selectedPrinter }) {
  
  const {
    invoiceNumber,
    invoiceDate,
    dueDate,
    fbrInvoiceNumber,
    clientName,
    clientAddress,
    saleBy,
  } = useContext(Statee);
  const { newSalesProduct } = ((state)=> state.newSalesProduct)
  const {user} = useSelector((state)=> state.user)
// useEffect(() => {
//   first

//   return () => {
//     second
//   }
// }, [])

  return (
    <>
      {user?.user?.printerId?.printerType === "Laser" ? (
      <table  style={{whiteSpace:"nowrap",justifyContent: "center", marginTop: "20px", marginLeft: "100px", borderBottom: "2px solid black"}} >
        <tr>
          <td ><span className="font-bold td1">Customer Name:&nbsp;&nbsp;</span>{clientName}</td>
          <td ><span className="font-bold td1"  style={{ marginLeft: "80px"}}>Cell No:&nbsp;&nbsp;</span>{clientAddress}</td>
          <td></td>
        </tr>
        <tr>
        <td>
            <span className="font-bold td1">Invoice number:&nbsp;&nbsp;</span>
            {invoiceNumber}
          </td>
        <td>
          <span className="font-bold td1" style={{ marginLeft: "80px"}}>Invoice date:&nbsp;&nbsp;</span> {invoiceDate}
          </td>
          
          
        </tr>
        <tr>
          <td ><span className="font-bold td1">Generated By:&nbsp;&nbsp;</span>{saleBy}</td>
          <td>
            <span className="font-bold td1" style={{ marginLeft: "80px"}}>FBR Invoice number:&nbsp;&nbsp;</span>{" "}
            {fbrInvoiceNumber}
          </td>
        </tr>
      </table>
      ):(
        <div style={{ width: '100%', overflowX: 'auto',  marginTop: "-30px", marginBottom: "0px",whiteSpace:"nowrap" }}>
      <table  className="mt-10 table1" style={{ fontSize: '10px',whiteSpace:"nowrap" }}>
      <tr tyle={{ marginTop: "-10px", padding: "0px", marginBottom: "-10px" }}>
        <td className="font-bold td1">
        <span className="font-bold td1">Customer Name:</span>{clientName}</td>
      </tr>
      <tr tyle={{ marginTop: "-10px", padding: "0px", marginBottom: "-10px" }}>
        <td>
          {" "}
          <span className="font-bold td1">Invoicer number:</span>{" "}
          {invoiceNumber}
        </td>
      </tr>
      <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
        <td className="font-bold td1">
        <span className="font-bold td1">Cell No:</span>{clientAddress}</td>
      </tr>
      <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
        <td>
          <span className="font-bold td1">Invoice date:</span> {invoiceDate}
        </td>
      </tr>
      <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
        <td className="font-bold td1">
        <span className="font-bold td1">Generated By:</span>{saleBy}</td>
      </tr>
      <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
        <td>
          <span className="font-bold td1">FBR Invoicer number:</span>{" "}
          {fbrInvoiceNumber}
        </td>
      </tr>
    </table>
    </div>
      )}
    </>
  );
}
