export const pakistan = {
  pakistan: [
    {
      "Islamabad Ali Pur": [
        "Arslan Town",
        "Balti Colony",
        "Chatha bakhtawar",
        "Chirah",
        "Dhoke Jabi",
        "Farash Town",
        "Hamdani Town",
        "Irfan Abad",
        "Jung Sayedan",
        "Kirpa Road",
        "Nilor",
        "Old Radio Pakistan",
        "Panjgran",
        "Phulgran",
        "Satra Meel",
        "Shaheen Town",
        "Sultana Foundation",
        "Taramri Chowk",
        "Thanda Pani",
      ],
    },
    { "Islamabad B 17": ["Sector B 17"] },
    { "Islamabad Bahria Enclave": ["Sector H", "Sector I"] },
    {
      "Islamabad Bahria Town": [
        "Phase 1",
        "Phase 2",
        "Phase 3",
        "Phase 4",
        "Phase 5",
        "Phase 6",
        "Phase 7",
        "Phase 8",
      ],
    },
    {
      "Islamabad Banni Gaala": [
        "Abbasi Road Street 14 B",
        "Akram Road",
        "Dr. AQ Khan School Road",
        "Ghaus Al Azam Road",
        "Green Valley Society Islamabad",
        "Imran Khan Chowk",
        "Imran Khan Road",
        "Khyber City Town",
        "Korang Road",
        "Lake View Lanes Colony",
        "Lakhwal",
        "Muzaffar Khan Road",
        "North Banni Galla",
        "Pakistan Colony",
        "Qasim Avenue",
        "Raja Ashraf Road",
        "River Side Enclave",
      ],
    },
    {
      "Islamabad Bhara Kahu": [
        "17 Mile",
        "Abdullah Town",
        "Ahmad Town",
        "Ali Town Kundi",
        "Ameen Abbasi Town",
        "Azmat Town",
        "Belgium Town",
        "Colonel Aman Ullah Road",
        "Company Road",
        "Dhoke Mohri",
        "Jillani Town",
        "Kiani Road",
        "Kot Hathyal",
        "Margallah Valley",
        "Mohalla Syadan",
        "Mungo Town",
        "Muslim Town",
        "Nai Abadi",
        "Prince Road",
        "PTV Colony",
        "Sehri Chowk",
        "University Town",
        "Usman Abad",
      ],
    },
    {
      "Islamabad Chak Shahzad": [
        "Chak Shehzad Farms",
        "COMSATS University",
        "Gulshan E Alhuda",
        "Jinnah Complex",
        "NIH Hospital",
        "Shahzad Town",
      ],
    },
    {
      "Islamabad Chatta Bakhtawar": [
        "Chatta Road",
        "Green Avenue Phase 1",
        "Green Avenue Phase 2",
        "Hostel City",
        "Junaid Mughal Town",
        "Kurri Road",
        "Mohra Noor",
        "New Chatta Bakhtawar",
        "Park Enclave",
        "Park View",
      ],
    },
    {
      "Islamabad D 12": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    { "Islamabad D 13": ["Sector D 13"] },
    { "Islamabad D 17": ["Sarai Kharbuza", "Sector D 17"] },
    {
      "Islamabad DHA": ["Phase 1", "Phase 2", "Phase 3", "Phase 4", "Phase 5"],
    },
    { "Islamabad E 10": ["Sector 1"] },
    {
      "Islamabad E 11": [
        "Al Mehar Colony",
        "Golra Sharif",
        "Mehran Complex",
        "Sector 1",
        "Sector 2",
        "Sector 4",
      ],
    },
    { "Islamabad E 18": ["Sector E 18"] },
    {
      "Islamabad E 7": [
        "Markaz",
        "Sector 1",
        "Sector 3",
        "Sector 3",
        "Sector 4",
      ],
    },
    { "Islamabad E 8": ["Sector 1", "Sector 2"] },
    { "Islamabad E 9": ["Sector 1", "Sector 2", "Sector 3", "Sector 4"] },
    {
      "Islamabad F 10": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad F 11": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    { "Islamabad F 17": ["Sector F 17"] },
    { "Islamabad F 5": ["Sector 1", "Sector 2"] },
    {
      "Islamabad F 6": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad F 7": [
        "Said Pur Village",
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad F 8": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad G 10": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad G 11": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad G 12": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad G 13": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    { "Islamabad G 14": ["Sector 1", "Sector 2", "Sector 3", "Sector 4"] },
    {
      "Islamabad G 15": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad G 5": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad G 6": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad G 7": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad G 8": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad G 9": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad Ghauri Town": [
        "Dhoke Gangal",
        "Ghauri Town Phase 1",
        "Ghauri Town Phase 2",
        "Ghauri Town Phase 3",
        "Ghauri Town Phase 4",
        "Ghauri Town Phase 5",
        "Ghauri Town Phase 6",
        "Ghauri Town Phase 7",
        "Ghouri Garden",
        "Kalma Chowk",
        "Koral Chowk",
        "Madina Town",
        "Marwa Town",
        "Sanam Chowk",
        "Shareef Abad",
      ],
    },
    {
      "Islamabad H 10": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad H 11": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad H 12": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad H 13": [
        "Abdullah Garden",
        "Abu Bakar Block",
        "Ali Bakhish Town",
        "Ali Block",
        "Capital Homes Colony",
        "Gulzaar E Madina Town",
        "Hamza Block",
        "Hashmi Town",
        "Khayaban E Faiz",
        "Khayam Town",
        "Muhammadi Block",
        "Paris City Block E",
        "Paris City Block F",
        "Paris City Block H",
        "Quaid E Azam Hospital",
        "Shams Colony",
        "Suleman Town",
        "Umer Block",
        "Usman Block",
      ],
    },
    { "Islamabad H 15": ["Sector H 15"] },
    {
      "Islamabad H 8": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad H 9": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad I 10": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad I 11": [
        "NESCOM",
        "Sabzi Mandi",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad I 12": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad I 14": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    { "Islamabad I 16": ["Sector I 16"] },
    {
      "Islamabad I 8": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad I 9": [
        "Markaz",
        "Sector 1",
        "Sector 2",
        "Sector 3",
        "Sector 4",
      ],
    },
    {
      "Islamabad Jhangi Syedian": [
        "Chongi 26",
        "Islamabad International Airport",
        "Jhangi Syedian",
        "Muhammadi Town",
      ],
    },
    {
      "Islamabad Rawal Town": [
        "Margalla Town",
        "NARC Colony",
        "Orchard Scheme",
      ],
    },
    {
      "Islamabad Sohan": [
        "Abbasi Road",
        "Al Hajh Hukamdad Road",
        "Al Qaim Town",
        "Ashraf Town",
        "Awaan Town",
        "Azhar Town",
        "Burma",
        "Laal Market",
        "Madni Town",
        "Malik Tahir Town",
        "Nawab Town",
        "Razaq Valley Road",
        "Sohan",
      ],
    },
    {
      "Islamabad Tarlai Kalan": [
        "Ghazi Shah Imam Road",
        "Gulberg Town",
        "Gulshan E Tarlai",
        "Irfanabad Town",
        "Jagiot Road",
        "Mehrban Town",
        "Sarfraz Town",
        "Sher Ali Town",
        "Talai Kalan",
        "Taramri",
      ],
    },
    { Tarnol: ["Tarnol"] },
    {
      "Rawalpindi Adyala": [
        "Adyala Road",
        "Ali Town",
        "ARL Colony",
        "Army Colony",
        "Askari 14",
        "Askari 7",
        "Baqir Colony",
        "Caltex Road",
        "Clifton Town",
        "Defence Road",
        "Dhok Juma",
        "Fort Road",
        "Garden Villa",
        "Green Villa",
        "Gulbahar Colony",
        "Gulshan Abad",
        "Hill View Lane",
        "Janjua Town",
        "Kehkeshan Colony",
        "Khawaja Cooperation",
        "Lalazar Estate",
        "Morgah",
        "Mubarik Lane",
        "Munawar Colony",
        "New Lalazar",
        "Old Lalazar",
        "Raja Akram",
        "Sarmarzar",
        "Sher Zaman Colony",
        "Tulsa Road",
      ],
    },
    {
      "Rawalpindi Airport society": [
        "Civic Center",
        "Iqbal Road",
        "Obaid Road",
        "Wakeel Colony",
      ],
    },
    {
      "Rawalpindi Bahria town": [
        "Abu Bakr Block",
        "Ali Block",
        "Bahria Town Gate GT Road",
        "Civic Center",
        "College Road",
        "Garden City",
        "Khalid Block",
        "Overseas Enclave",
        "Phase 1",
        "Phase 2",
        "Phase 3",
        "Phase 4",
        "Phase 5",
        "Phase 6",
        "Phase 7",
        "Phase 8",
        "Safari Homes",
        "Safari Villa 1 3",
        "Umer Block",
        "Usman Block",
      ],
    },
    { "Rawalpindi CBR Town": ["CBR Town Block B To D"] },
    {
      "  Rawalpindi Chaklala": [
        "AECHS",
        "Afzal Town",
        "Airport Chowk",
        "Askari 1",
        "Askari10",
        "Askari12",
        "Askari13",
        " Askari2",
        "Askari 3",
        "Askari 4",
        "Askari 5",
        "Askari 6",
        "Askari 8",
        "Askari 9",
        "Ayub Colony",
        "Ayub Park",
        "Azeem Town",
        "Banaras Colony",
        "Bostan Khan Road",
        "Burma Shell",
        "Chaklala Village",
        "Civil Line",
        "Commercial Market",
        "Daad Khan Colony",
        "Dhok Chodhrian",
        "Dhok Hafiz",
        "Dhok Kashmirian",
        "Fazal Town Phase 1 2",
        "Ghareeb Abad",
        "Gracey Lane",
        "Gulistan Colony",
        "Gulzar e Quaid",
        "Gulzar E Quaid Extension",
        "High Court Road",
        "Jaan Colony",
        "Jhanda Chichi",
        "Judicial Colony",
        "Katchehri Chowk",
        "Khayaban E Tanvir",
        "Muree Brewrey Office",
        "New Afzal Town",
        "Noorani Muhalla",
        "Palm City",
        "Park Road",
        "Qadeer Market",
        "Rahim Abad",
        "Railway Scheme 1 To 4",
        "Railway Scheme 9",
        "Rose Lane",
        "Scheme 1",
        "Scheme 2",
        "Scheme 3",
        "Shah Faisal Colony",
        "Shah Khalid Colony",
        "Wallayat Colony",
      ],
    },
    {
      "Rawalpindi DHA": [
        "Askari Tower 1 2",
        "Babu Market",
        "DHA Gate GT Road",
        "DHA Phase 3",
        "Emaar M 1 to M 7",
        "Fauji Foundation Hospita",
        "Giga Mall",
        "Phase 1",
        "Phase 2",
        "Phase 5",
        "Zaraj Housing Society",
      ],
    },
    {
      "Rawalpindi Dhamyal": [
        "Ahmed Abad",
        "Ashraf Colony",
        "Bakra Mandi",
        "Banni Stop",
        "Chakri Road",
        "Dhamial Camp",
        "Dhamial Road",
        "Dhoke Mangtal",
        "Gulshan E Iqbal",
        "Lala Rukh Colony",
        "alazar Estate 2",
        "Liaqat Colony",
        "Qasim Base",
        "Quaid E Azam Colony",
        "Shadman Town",
      ],
    },
    {
      "Rawalpindi Dhok Gangal": [
        "Babar Colony",
        "Chatri Chowk",
        "Dhok Nussah",
        "KRL Road",
        "Rajgan Colony",
        "Shaheen Town",
      ],
    },
    {
      "Rawalpindi Dhok Kala Khan": [
        "Gulistan E Jinah",
        "Madina Town",
        "Murghi Mandi",
        "Ojhri Camp",
        "Taxi Stand",
      ],
    },
    {
      "Rawalpindi Fizaiya Colony": [
        "KRL Colony",
        "Mangral Tow",
        "Springs Apartments",
      ],
    },
    {
      " Rawalpindi Gulraiz": [
        "Commerical",
        "Phase 1",
        "Phase 2",
        "Phase 3",
        "Phase 4",
        "Phase 5",
        "Phase 6",
      ],
    },
    { "Rawalpindi Humak": ["Industrial Triangle Kahuta", "Model Town Humak"] },
    {
      "Rawalpindi IJP Road": [
        "Ameen Town",
        "Awan Market",
        "Bangash Colony",
        "Carriage Factory",
        "Dhok Hassu",
        "Dhok Najju",
        "Fauji Colony",
        "Kacha Stop",
        "Khyaban Sector 1 To 3",
        "Khyaban Sector 4A",
        "Khyaban Sector 4B",
        "Marble Factory Road",
        "New Katarian",
        "Pindora Chungi",
        "Pirwadhai Adda",
        "Railway Hospital",
      ],
    },
    {
      "Rawalpindi Khanna": [
        "Al Noor Colony",
        "Gondal Market",
        "Karimabad",
        "Noora Road",
        "Professors Colony",
        "Sarfraz Marke",
        "Shaheen Colony",
      ],
    },
    {
      "Rawalpindi Kuri Road": [
        "Ali Abad",
        "Dhoke Ali Akba",
        "Farooq E Azam",
        "Haroon Chowk",
        "Ilyas Town",
      ],
    },
    {
      "Rawalpindi Lalkurti": [
        "Alamgir Road",
        "Aslam Shaheed Road",
        "Aziz Bhatti Road",
        "CMH",
        "Dheri Hassan Abad",
        "Harley Street",
        "Indus Road",
        "Khadim Hussain Road",
        "Knight Road",
        "Sabzazar",
        "Tahli Mori",
        "Tufail Road",
      ],
    },
    { "Rawalpindi Lohi Bhair": ["Dhok Kashmirian", "Lohi Bhair"] },
    {
      "Rawalpindi Media Town": [
        "Federation Housing Society",
        "Media Town Block A To D",
      ],
    },
    {
      "Rawalpindi Muree Road": [
        "Akbar Market",
        "Ali Nawaz Chowk",
        "Amar Pura",
        "Awan Town",
        "Benazir Hospital",
        "Circular Road",
        "Dhok Farman Ali",
        "Dhok Khabba",
        "Glass Factory",
        "Haider Camp",
        "Iqbal Camp",
        "Iqbal Town",
        "Marir Hassan",
        "Millat Colony",
        "Mukha Singh State",
        "Rawal Park",
        "Rawalpindi Institute Of Cardiology RIC",
        "Rawalpindi Medical University",
        "Sir Syed Chowk",
        "Sultan Ka Khuh",
        "Tamasip Abad",
        "Thana Waris Khan",
        "Tipu Road",
        "Waris Khan",
      ],
    },
    {
      "Rawalpindi Muslim Town": [
        "Bihari Colony",
        "Khurram Colony",
        "Muhammadi Colony",
      ],
    },
    {
      "Rawalpindi National Police Foundation": [
        "Block A",
        "Block B",
        "Block C",
        "Block D",
        "Block E",
        "Block F",
        "National Police Foundation Block A To F",
      ],
    },
    { "Rawalpindi Pakistan Town": ["Korang Town", "Phase 1", "Phase 2"] },
    {
      "Rawalpindi Peshawar Road": [
        "26 # Chungi",
        "Afshan Colony",
        "Aliabad",
        "Allahabad",
        "Ashayana Chowk",
        "Awan Town",
        "Bait E Sada Colony",
        "Bakery Chowk",
        "Bhata Chowk",
        "Bilal Umer Shaheed Colony",
        "Cantt View Colony",
        "Charing Cross",
        "Chour Chowk",
        "CMT Golra",
        "Cobb Line",
        "Dhok Banaras",
        "Dhok Chodhrian",
        "Dhok Gujran",
        "Dhok Mustaqim",
        "Faisal Colony",
        "Friend's Colony",
        "Friend's Colony",
        "Gulshan E Nayab",
        "Ilyas Colony",
        "Jhangi Syedian",
        "Kainat Adda",
        "Koh E Noor Mil",
        "KRL Flats",
        "Madina Town",
        "Meherabad",
        "Misrial Road",
        "Mohalla Qureshian",
        "Mukrram Town",
        "Nagi Road",
        "Najam Shaheed Road",
        "Naseer Abad",
        "New Chakra",
        "Niazi Town",
        "Officer's Colony",
        "OGDCL Society",
        "Old Chakra",
        "Parade Lane",
        "Peshawar Road Lane 1",
        "Peshawar Road Lane 3",
        "Peshawar Road Lane 4",
        "Peshawar Road Lane5",
        "Peshawar Road Lane 6",
        "Peshawar Road Lane 7",
        "c",
        "Pirwadhai Mor",
        "Postal Colony",
        "Qasimabad",
        "Qasim Market",
        "Quaid E Azam International Hospital",
        "Race Course Road",
        "Raja Akram Road",
        "Range Road",
        "Shabbir Lane East",
        "Shabbir Lane West",
        "Shalley Valley",
        "Transit Camp",
      ],
    },
    {
      "Rawalpindi Raja Bazar": [
        "Akaal Garh",
        "Arjun Nagar",
        "Asghar Mall Scheme",
        "Bagh Sardaran",
        "Bagh Sardaran",
        "Bokra Road",
        "Borh Bazar",
        "Boring Road",
        "Chungi Number 4",
        "Darya Abad",
        "Dhoke Dalal",
        "Dhok Mangtal",
        "Dhok Matkiyal",
        "Dhok Ratta",
        "Dingi Khoi",
        "Eid Gah Sharif",
        "Fawara Chowk",
        "Gawalmandi",
        "Imperial Market",
        "Iqbal Road",
        "Kohati Bazar",
        "Liaqat Bagh",
        "Mohalla Shah",
        "Mohan Pura",
        "Moti Baza",
        "New Sarafa Bazar",
        "Pirwadhi",
        "Railway Colony",
        "Railway Scheme 7",
        "Ratta Amral",
        "Sarafa Bazar",
        "Thana Ganj Mandi",
        "Urdu Bazar",
      ],
    },
    { "Rawalpindi Urdu Bazar": ["Kohsar Market", "Rawat Bazar", "T Chowk"] },
    {
      "Rawalpindi Saddar": [
        "Adam Ji Road",
        "AFIC",
        "Babu Muhalla",
        "Bank Road",
        "Chota Bazar",
        "City Center",
        "GPO Chowk",
        "Haider Road",
        "Hathi Chowk",
        "Kamran Market",
        "Kashmir Road",
        "Koila Center",
        "Muhammad Hussain Road",
        "Panj Sarki",
        "Rawalpindi Cantonment Hospital",
        "Saadi Road",
        "Signals Officer Mess",
        "Sir Syed Road",
        "Station Morr",
      ],
    },
    {
      "Rawalpindi Sadiqabad": [
        "8 Number Chungi",
        "Afandi Colony",
        "Affandi Colony",
        "Band Khanna Road",
        "Bilal Colony",
        "Chah Sultan",
        "Chirah Chowk",
        "Dhoke Paracha",
        "Dhok Piran Faqiran",
        "Falcon Complex",
        "Haji Chowk",
        "Iqbal Town",
        "Jahaz Ground",
        "Jalebi Chowk",
        "Nishtar Street",
        "Sadiqabad Mor",
        "Transformer Chowk",
      ],
    },
    {
      "Rawalpindi Satellite Town": [
        "6th Road",
        "7th Road",
        "Chandni Chowk",
        "Commercial Market",
        "Haidri Chowk",
        "Holy Family Hospital",
        "Kali Tanki",
        "Katarian Market",
        "Mohalla Raja Sultan",
        "National Market",
        "Phagwari",
        "Saidpur Road",
        "Satellite Town Block A",
        "Satellite Town Block C",
        "Satellite Town Block D",
        "Satellite Town Block E",
        "Satellite Town Block F",
        "Shamsabad",
        "Siddiqui Chowk",
      ],
    },
    {
      "Rawalpindi Tench": [
        "22 Number Chungi",
        "Abid Majeed Road",
        "Aziz Abad",
        "Baraf Khana Chowk",
        "Dhok Syedan",
        "Dispensary Chowk",
        "Girja Road",
        "Jan Colony",
        "Kamal Abad",
        "People's Colony",
        "TenchStop",
        "Tench Bhata",
      ],
    },
  ],
};
