export const POST_SALE_PRODUCT_TO_FISCAL_REQUEST = "POST_SALE_PRODUCT_TO_FISCAL_REQUEST"
export const POST_SALE_PRODUCT_TO_FISCAL_SUCCESS = "POST_SALE_PRODUCT_TO_FISCAL_SUCCESS"
export const POST_SALE_PRODUCT_TO_FISCAL_FAIL = "POST_SALE_PRODUCT_TO_FISCAL_FAIL"

export const POST_SALE_PRODUCT_REQUEST = "POST_SALE_PRODUCT_REQUEST"
export const POST_SALE_PRODUCT_SUCCESS = "POST_SALE_PRODUCT_SUCCESS"
export const POST_SALE_PRODUCT_FAIL = "POST_SALE_PRODUCT_FAIL"

export const GET_SALE_PRODUCT_REQUEST = "GET_SALE_PRODUCT_REQUEST"
export const GET_SALE_PRODUCT_SUCCESS = "GET_SALE_PRODUCT_SUCCESS"
export const GET_SALE_PRODUCT_FAIL = "GET_SALE_PRODUCT_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS"