export const GET_TRANSFER_PRODUCT_REQUEST = "GET_TRANSFER_PRODUCT_REQUEST"
export const GET_TRANSFER_PRODUCT_SUCCESS = "GET_TRANSFER_PRODUCT_SUCCESS"
export const GET_TRANSFER_PRODUCT_FAIL = "GET_TRANSFER_PRODUCT_FAIL"