export const GLOBAL_RATES_REQUEST = "GLOBAL_RATES_REQUEST";
export const GLOBAL_RATES_SUCCESS = "GLOBAL_RATES_SUCCESS";
export const GLOBAL_RATES_FAIL = "GLOBAL_RATES_FAIL";


export const POST_GLOBAL_RATES_REQUEST = "POST_GLOBAL_RATES_REQUEST";
export const POST_GLOBAL_RATES_SUCCESS = "POST_GLOBAL_RATES_SUCCESS";
export const POST_GLOBAL_RATES_FAIL = "POST_GLOBAL_RATES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
