export const LOCAL_RATES_REQUEST = "LOCAL_RATES_REQUEST";
export const LOCAL_RATES_SUCCESS = "LOCAL_RATES_SUCCESS";
export const LOCAL_RATES_FAIL = "LOCAL_RATES_FAIL";

export const POST_LOCAL_RATES_REQUEST = "POST_LOCAL_RATES_REQUEST";
export const POST_LOCAL_RATES_SUCCESS = "POST_LOCAL_RATES_SUCCESS";
export const POST_LOCAL_RATES_FAIL = "POST_LOCAL_RATES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
