import { useContext } from "react";
// import { State } from "./context/stateContext";
import { Statte } from "./context/stateContext";
import "../stylee/tableStyling.css";
import { useSelector } from "react-redux";
import "./transferReciptCss/transfer.css";
export default function Dates({ selectedPrinter }) {
  const {
    invoiceNumber,
    invoiceDate,
    transferFrom,
    transferTo,
    transferBy,
    selectedRadioOption,
    setSelectedRadioOption,
  } = useContext(Statte);
  const { user } = useSelector((state) => state.user);
  return (
    <>
      {user?.user?.printerId?.printerType === "Laser" ? (
        <>
          <div className="InvoiceLaserFirstRecordDiv">
            <div className="consolidateLaserQuantity">
              <h5>Transfer from :</h5>
              <p>{selectedRadioOption}</p>
            </div>
            <div className="consolidateLaserProductCode">
              <h5>Invoicer number:</h5>
              <p>{invoiceNumber}</p>
            </div>
          </div>
          <div className="InvoiceLaserFirstRecordDiv">
            <div className="consolidateLaserQuantity">
              <h5>Transfer To :</h5>
              <p> {transferTo}</p>
            </div>
            <div className="consolidateLaserProductCode">
              <h5>Invoice date:</h5>
              <p>{invoiceDate}</p>
            </div>
          </div>
          <div className="InvoiceLaserFirstRecordDiv">
            <div className="consolidateLaserQuantity">
              <h5>Generated By::</h5>
              <p> {transferBy}</p>
            </div>
          </div>
        </>
      ) : (
        // <>
        // <table  style={{whiteSpace:"nowrap",justifyContent: "center", marginTop: "20px", marginLeft: "100px", borderBottom: "2px solid black"}}>
        //   <tr>
        //     <td className=" td1">
        //       <span className="font-bold td1" > Transfer from :&nbsp;&nbsp;</span>{" "}
        //       {selectedRadioOption}
        //     </td>
        //     <td>
        //       <span className="font-bold td1" style={{ marginLeft: "80px"}}>Invoicer number:&nbsp;&nbsp;</span>
        //       {invoiceNumber}
        //     </td>
        //   </tr>
        //   <tr>
        //     <td className=" td1">
        //       <span className="font-bold td1">Transfer To :&nbsp;&nbsp;</span> {transferTo}
        //     </td>
        //     <td>
        //       <span className="font-bold td1" style={{ marginLeft: "80px"}}>Invoice date:&nbsp;&nbsp;</span> {invoiceDate}
        //     </td>
        //   </tr>
        //   <tr>
        //     <td className=" td1">
        //       <span className="font-bold td1">Generated By:&nbsp;&nbsp;</span> {transferBy}
        //     </td>
        //   </tr>
        // </table>
        // </>
        <>
          <div
            style={{
              width: "100%",
              overflowX: "auto",
              marginTop: "-30px",
              marginBottom: "0px",
              whiteSpace: "nowrap",
            }}
          ></div>
          <table className="table1" style={{ fontSize: "10px" }}>
            <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
              <td className=" td1">
                <span className="font-bold td1"> Transfer from : </span>{" "}
                {selectedRadioOption}
              </td>
            </tr>
            <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
              <td>
                <span className="font-bold td1">Invoicer number:</span>{" "}
                {invoiceNumber}
              </td>
            </tr>
            <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
              <td className=" td1">
                <span className="font-bold td1">Transfer To : </span>{" "}
                {transferTo}
              </td>
            </tr>
            <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
              <td>
                <span className="font-bold td1">Invoice date:</span>{" "}
                {invoiceDate}
              </td>
            </tr>
            <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
              <td className=" td1">
                <span className="font-bold td1">Generated By: </span>{" "}
                {transferBy}
              </td>
            </tr>
          </table>
        </>
      )}
    </>
  );
}
